### ISSUE TITLE
Command line functionality

### ISSUE THREAD

**Issue by DoganM95** [pyriell/omniconvert#1]
I know, i know.. the tool is old now (2012),
but does this app support command line arguments?

I would love to write a script that converts all `.pnach` files in a directory using a loop by running the `omniconvert.exe` with arguments e.g. `--in "ARMAX" --out "Unencrypted-standard" --outPath "C:/converted"` on each.

**Comment by pyriell** [comment]
Afraid not.  I agree that'd be a useful tool.  However, when I designed this, there were maybe 100 power-users on the planet who might have wanted to use features like that with any regularity, and I just wasn't focused on them.  I wanted to pull all the encryption/conversion work into one tool as much as possible, but more to speed up or cut down on conversion requests that included a handful of codes than to service someone looking to port their entire collection of codes from AR MAX to pnach files.

I had something like what you want sort of half-finished ages ago (separate application), but work and illnesses in the family kept pulling me away.  Eventually, it just didn't seem worth finishing for a variety of reasons.  Sorry I can't be more help.

I don't think there's a utility that suits your specific case.  Misfire has something close to that for the CodeBreaker, though.  I can't recall all its functionality.  I want to say it doesn't do any conversions whatsoever, and the input expected is fairly rigid.  So that probably won't help you, unfortunately.

**Comment by DoganM95** [comment]
No problem, i get your point.
Your answer was helpful to me nevertheless, thank you!
